//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace WcfServiceStudent
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class StudentEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new StudentEntities object using the connection string found in the 'StudentEntities' section of the application configuration file.
        /// </summary>
        public StudentEntities() : base("name=StudentEntities", "StudentEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StudentEntities object.
        /// </summary>
        public StudentEntities(string connectionString) : base(connectionString, "StudentEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StudentEntities object.
        /// </summary>
        public StudentEntities(EntityConnection connection) : base(connection, "StudentEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_student> tbl_student
        {
            get
            {
                if ((_tbl_student == null))
                {
                    _tbl_student = base.CreateObjectSet<tbl_student>("tbl_student");
                }
                return _tbl_student;
            }
        }
        private ObjectSet<tbl_student> _tbl_student;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<StudenDetailsView> StudenDetailsViews
        {
            get
            {
                if ((_StudenDetailsViews == null))
                {
                    _StudenDetailsViews = base.CreateObjectSet<StudenDetailsView>("StudenDetailsViews");
                }
                return _StudenDetailsViews;
            }
        }
        private ObjectSet<StudenDetailsView> _StudenDetailsViews;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_student EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_student(tbl_student tbl_student)
        {
            base.AddObject("tbl_student", tbl_student);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the StudenDetailsViews EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStudenDetailsViews(StudenDetailsView studenDetailsView)
        {
            base.AddObject("StudenDetailsViews", studenDetailsView);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StudentModel", Name="StudenDetailsView")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class StudenDetailsView : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new StudenDetailsView object.
        /// </summary>
        /// <param name="expr1">Initial value of the Expr1 property.</param>
        /// <param name="id">Initial value of the ID property.</param>
        public static StudenDetailsView CreateStudenDetailsView(global::System.Int32 expr1, global::System.Int32 id)
        {
            StudenDetailsView studenDetailsView = new StudenDetailsView();
            studenDetailsView.Expr1 = expr1;
            studenDetailsView.ID = id;
            return studenDetailsView;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Expr1
        {
            get
            {
                return _Expr1;
            }
            set
            {
                if (_Expr1 != value)
                {
                    OnExpr1Changing(value);
                    ReportPropertyChanging("Expr1");
                    _Expr1 = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Expr1");
                    OnExpr1Changed();
                }
            }
        }
        private global::System.Int32 _Expr1;
        partial void OnExpr1Changing(global::System.Int32 value);
        partial void OnExpr1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Expr2
        {
            get
            {
                return _Expr2;
            }
            set
            {
                OnExpr2Changing(value);
                ReportPropertyChanging("Expr2");
                _Expr2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Expr2");
                OnExpr2Changed();
            }
        }
        private global::System.String _Expr2;
        partial void OnExpr2Changing(global::System.String value);
        partial void OnExpr2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Expr3
        {
            get
            {
                return _Expr3;
            }
            set
            {
                OnExpr3Changing(value);
                ReportPropertyChanging("Expr3");
                _Expr3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Expr3");
                OnExpr3Changed();
            }
        }
        private global::System.String _Expr3;
        partial void OnExpr3Changing(global::System.String value);
        partial void OnExpr3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Expr4
        {
            get
            {
                return _Expr4;
            }
            set
            {
                OnExpr4Changing(value);
                ReportPropertyChanging("Expr4");
                _Expr4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Expr4");
                OnExpr4Changed();
            }
        }
        private global::System.String _Expr4;
        partial void OnExpr4Changing(global::System.String value);
        partial void OnExpr4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StudentName
        {
            get
            {
                return _StudentName;
            }
            set
            {
                OnStudentNameChanging(value);
                ReportPropertyChanging("StudentName");
                _StudentName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StudentName");
                OnStudentNameChanged();
            }
        }
        private global::System.String _StudentName;
        partial void OnStudentNameChanging(global::System.String value);
        partial void OnStudentNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IndexNumber
        {
            get
            {
                return _IndexNumber;
            }
            set
            {
                OnIndexNumberChanging(value);
                ReportPropertyChanging("IndexNumber");
                _IndexNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IndexNumber");
                OnIndexNumberChanged();
            }
        }
        private global::System.String _IndexNumber;
        partial void OnIndexNumberChanging(global::System.String value);
        partial void OnIndexNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String JMBG
        {
            get
            {
                return _JMBG;
            }
            set
            {
                OnJMBGChanging(value);
                ReportPropertyChanging("JMBG");
                _JMBG = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("JMBG");
                OnJMBGChanged();
            }
        }
        private global::System.String _JMBG;
        partial void OnJMBGChanging(global::System.String value);
        partial void OnJMBGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sex
        {
            get
            {
                return _Sex;
            }
            set
            {
                OnSexChanging(value);
                ReportPropertyChanging("Sex");
                _Sex = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Sex");
                OnSexChanged();
            }
        }
        private global::System.String _Sex;
        partial void OnSexChanging(global::System.String value);
        partial void OnSexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> BirthDate
        {
            get
            {
                return _BirthDate;
            }
            set
            {
                OnBirthDateChanging(value);
                ReportPropertyChanging("BirthDate");
                _BirthDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BirthDate");
                OnBirthDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _BirthDate;
        partial void OnBirthDateChanging(Nullable<global::System.DateTime> value);
        partial void OnBirthDateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StudentModel", Name="tbl_student")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_student : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_student object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static tbl_student Createtbl_student(global::System.Int32 id)
        {
            tbl_student tbl_student = new tbl_student();
            tbl_student.ID = id;
            return tbl_student;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StudentName
        {
            get
            {
                return _StudentName;
            }
            set
            {
                OnStudentNameChanging(value);
                ReportPropertyChanging("StudentName");
                _StudentName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StudentName");
                OnStudentNameChanged();
            }
        }
        private global::System.String _StudentName;
        partial void OnStudentNameChanging(global::System.String value);
        partial void OnStudentNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IndexNumber
        {
            get
            {
                return _IndexNumber;
            }
            set
            {
                OnIndexNumberChanging(value);
                ReportPropertyChanging("IndexNumber");
                _IndexNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IndexNumber");
                OnIndexNumberChanged();
            }
        }
        private global::System.String _IndexNumber;
        partial void OnIndexNumberChanging(global::System.String value);
        partial void OnIndexNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String JMBG
        {
            get
            {
                return _JMBG;
            }
            set
            {
                OnJMBGChanging(value);
                ReportPropertyChanging("JMBG");
                _JMBG = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("JMBG");
                OnJMBGChanged();
            }
        }
        private global::System.String _JMBG;
        partial void OnJMBGChanging(global::System.String value);
        partial void OnJMBGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sex
        {
            get
            {
                return _Sex;
            }
            set
            {
                OnSexChanging(value);
                ReportPropertyChanging("Sex");
                _Sex = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Sex");
                OnSexChanged();
            }
        }
        private global::System.String _Sex;
        partial void OnSexChanging(global::System.String value);
        partial void OnSexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> BirthDate
        {
            get
            {
                return _BirthDate;
            }
            set
            {
                OnBirthDateChanging(value);
                ReportPropertyChanging("BirthDate");
                _BirthDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BirthDate");
                OnBirthDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _BirthDate;
        partial void OnBirthDateChanging(Nullable<global::System.DateTime> value);
        partial void OnBirthDateChanged();

        #endregion
    
    }

    #endregion
    
}
